// Code generated by hand. Tests for multi-instance (会签) functionality.
package engine

import (
	"context"
	"testing"

	"github.com/lihongjie/workflow-go/instance"
	"github.com/lihongjie/workflow-go/spec"
	"github.com/lihongjie/workflow-go/storage/memstore"
)

func TestMultiInstance_Parallel(t *testing.T) {
	ctx := context.Background()
	s := memstore.New()
	t.Cleanup(func() { s.Close() })
	e := NewProcessEngine(s)

	def := &spec.ProcessDefinition{
		ID:      "mi_par",
		Key:     "mi_par",
		Version: 1,
		Elements: map[string]spec.FlowElement{
			"start": &spec.StartEvent{ID: "start"},
			"task": &spec.UserTask{
				ID: "task", Name: "Multi Task",
				LoopCharacteristics: &spec.LoopCharacteristics{
					Collection:      "items",
					ElementVariable: "item",
				},
			},
			"end": &spec.EndEvent{ID: "end"},
		},
		SequenceFlows: []*spec.SequenceFlow{
			{ID: "sf1", SourceRef: "start", TargetRef: "task"},
			{ID: "sf2", SourceRef: "task", TargetRef: "end"},
		},
		StartEventID: "start",
	}
	if err := s.CreateProcessDefinition(ctx, def); err != nil {
		t.Fatal(err)
	}

	// Start with a collection of 3 items.
	pi, err := e.StartProcessInstance(ctx, "mi_par", map[string]any{"items": []any{"a", "b", "c"}})
	if err != nil {
		t.Fatalf("StartProcessInstance: %v", err)
	}

	// Should have 3 active activities.
	activities, err := s.ListActiveActivities(ctx, pi.ID)
	if err != nil {
		t.Fatal(err)
	}
	if len(activities) != 3 {
		t.Fatalf("expected 3 parallel MI activities, got %d", len(activities))
	}

	// Verify loop counters.
	loopIDs := make(map[string]int)
	for _, ai := range activities {
		loopIDs[ai.MultiInstanceLoopID]++
		if ai.LoopCounter < 0 || ai.LoopCounter > 2 {
			t.Errorf("unexpected loop counter %d", ai.LoopCounter)
		}
	}
	if len(loopIDs) != 1 {
		t.Errorf("expected all activities to share one loopID, got %d", len(loopIDs))
	}

	// Complete all 3 tasks.
	for _, ai := range activities {
		if err := e.CompleteTask(ctx, ai.ID, nil); err != nil {
			t.Fatalf("CompleteTask: %v", err)
		}
	}

	// Process should be completed.
	pi, err = s.GetProcessInstance(ctx, pi.ID)
	if err != nil {
		t.Fatal(err)
	}
	if pi.State != instance.ProcessInstanceStateCompleted {
		t.Errorf("expected completed, got %q", pi.State)
	}
}

func TestMultiInstance_Sequential(t *testing.T) {
	ctx := context.Background()
	s := memstore.New()
	t.Cleanup(func() { s.Close() })
	e := NewProcessEngine(s)

	def := &spec.ProcessDefinition{
		ID:      "mi_seq",
		Key:     "mi_seq",
		Version: 1,
		Elements: map[string]spec.FlowElement{
			"start": &spec.StartEvent{ID: "start"},
			"task": &spec.UserTask{
				ID: "task", Name: "Seq Task",
				LoopCharacteristics: &spec.LoopCharacteristics{
					IsSequential:    true,
					Collection:      "items",
					ElementVariable: "item",
				},
			},
			"end": &spec.EndEvent{ID: "end"},
		},
		SequenceFlows: []*spec.SequenceFlow{
			{ID: "sf1", SourceRef: "start", TargetRef: "task"},
			{ID: "sf2", SourceRef: "task", TargetRef: "end"},
		},
		StartEventID: "start",
	}
	if err := s.CreateProcessDefinition(ctx, def); err != nil {
		t.Fatal(err)
	}

	pi, err := e.StartProcessInstance(ctx, "mi_seq", map[string]any{"items": []any{"x", "y"}})
	if err != nil {
		t.Fatalf("StartProcessInstance: %v", err)
	}

	// Should have 1 active activity (sequential starts one at a time).
	activities, err := s.ListActiveActivities(ctx, pi.ID)
	if err != nil {
		t.Fatal(err)
	}
	if len(activities) != 1 {
		t.Fatalf("expected 1 active activity (sequential), got %d", len(activities))
	}
	if activities[0].LoopCounter != 0 {
		t.Errorf("expected loop counter 0, got %d", activities[0].LoopCounter)
	}

	// Complete first -> should create second.
	if err := e.CompleteTask(ctx, activities[0].ID, nil); err != nil {
		t.Fatalf("CompleteTask 1: %v", err)
	}

	activities, err = s.ListActiveActivities(ctx, pi.ID)
	if err != nil {
		t.Fatal(err)
	}
	if len(activities) != 1 {
		t.Fatalf("expected 1 active after first complete, got %d", len(activities))
	}
	if activities[0].LoopCounter != 1 {
		t.Errorf("expected loop counter 1 for second, got %d", activities[0].LoopCounter)
	}

	// Complete second -> should finish.
	if err := e.CompleteTask(ctx, activities[0].ID, nil); err != nil {
		t.Fatalf("CompleteTask 2: %v", err)
	}

	pi, err = s.GetProcessInstance(ctx, pi.ID)
	if err != nil {
		t.Fatal(err)
	}
	if pi.State != instance.ProcessInstanceStateCompleted {
		t.Errorf("expected completed, got %q", pi.State)
	}
}

func TestMultiInstance_EmptyCollection(t *testing.T) {
	ctx := context.Background()
	s := memstore.New()
	t.Cleanup(func() { s.Close() })
	e := NewProcessEngine(s)

	def := &spec.ProcessDefinition{
		ID:      "mi_empty",
		Key:     "mi_empty",
		Version: 1,
		Elements: map[string]spec.FlowElement{
			"start": &spec.StartEvent{ID: "start"},
			"task": &spec.UserTask{
				ID: "task",
				LoopCharacteristics: &spec.LoopCharacteristics{
					Collection: "items",
				},
			},
			"end": &spec.EndEvent{ID: "end"},
		},
		SequenceFlows: []*spec.SequenceFlow{
			{ID: "sf1", SourceRef: "start", TargetRef: "task"},
			{ID: "sf2", SourceRef: "task", TargetRef: "end"},
		},
		StartEventID: "start",
	}
	if err := s.CreateProcessDefinition(ctx, def); err != nil {
		t.Fatal(err)
	}

	// Empty collection should skip the task and complete.
	pi, err := e.StartProcessInstance(ctx, "mi_empty", map[string]any{"items": []any{}})
	if err != nil {
		t.Fatalf("StartProcessInstance: %v", err)
	}
	if pi.State != instance.ProcessInstanceStateCompleted {
		t.Errorf("expected completed with empty collection, got %q", pi.State)
	}
}

func TestMultiInstance_ElementVariable(t *testing.T) {
	ctx := context.Background()
	s := memstore.New()
	t.Cleanup(func() { s.Close() })
	e := NewProcessEngine(s)

	// Use sequential mode so element variable is not overwritten.
	def := &spec.ProcessDefinition{
		ID:      "mi_var",
		Key:     "mi_var",
		Version: 1,
		Elements: map[string]spec.FlowElement{
			"start": &spec.StartEvent{ID: "start"},
			"task": &spec.UserTask{
				ID: "task",
				LoopCharacteristics: &spec.LoopCharacteristics{
					IsSequential:    true,
					Collection:      "items",
					ElementVariable: "current",
				},
			},
			"end": &spec.EndEvent{ID: "end"},
		},
		SequenceFlows: []*spec.SequenceFlow{
			{ID: "sf1", SourceRef: "start", TargetRef: "task"},
			{ID: "sf2", SourceRef: "task", TargetRef: "end"},
		},
		StartEventID: "start",
	}
	if err := s.CreateProcessDefinition(ctx, def); err != nil {
		t.Fatal(err)
	}

	pi, err := e.StartProcessInstance(ctx, "mi_var", map[string]any{"items": []any{"first", "second"}})
	if err != nil {
		t.Fatalf("StartProcessInstance: %v", err)
	}

	// First item variable should be set.
	item, err := s.GetVariable(ctx, pi.ID, "current")
	if err != nil {
		t.Fatal(err)
	}
	if item != "first" {
		t.Errorf("expected current = first, got %v", item)
	}
}

func TestMultiInstance_NoLoopCharacteristics(t *testing.T) {
	ctx := context.Background()
	s := memstore.New()
	t.Cleanup(func() { s.Close() })
	e := NewProcessEngine(s)

	// Regular UserTask (no MI) should behave normally.
	def := &spec.ProcessDefinition{
		ID:      "normal",
		Key:     "normal",
		Version: 1,
		Elements: map[string]spec.FlowElement{
			"start": &spec.StartEvent{ID: "start"},
			"task":  &spec.UserTask{ID: "task"},
			"end":   &spec.EndEvent{ID: "end"},
		},
		SequenceFlows: []*spec.SequenceFlow{
			{ID: "sf1", SourceRef: "start", TargetRef: "task"},
			{ID: "sf2", SourceRef: "task", TargetRef: "end"},
		},
		StartEventID: "start",
	}
	if err := s.CreateProcessDefinition(ctx, def); err != nil {
		t.Fatal(err)
	}

	pi, err := e.StartProcessInstance(ctx, "normal", nil)
	if err != nil {
		t.Fatalf("StartProcessInstance: %v", err)
	}
	activities, _ := s.ListActiveActivities(ctx, pi.ID)
	if len(activities) != 1 {
		t.Fatalf("expected 1 activity, got %d", len(activities))
	}
	if err := e.CompleteTask(ctx, activities[0].ID, nil); err != nil {
		t.Fatalf("CompleteTask: %v", err)
	}
	pi, _ = s.GetProcessInstance(ctx, pi.ID)
	if pi.State != instance.ProcessInstanceStateCompleted {
		t.Errorf("expected completed, got %q", pi.State)
	}
}
